## Deliverable 3. Create a Travel Itinerary Map.

In [8]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [14]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID        City Country  Max Temp Current Description      Lat  \
0        0     Ushuaia      AR     35.26    scattered clouds -54.8000   
1        1  Kaitangata      NZ     45.19       moderate rain -46.2817   
2        2      Mehamn      NO     55.31     overcast clouds  71.0357   
3        3     Mataura      NZ     46.47          light rain -46.1927   
4        4  Butaritari      KI     82.62     overcast clouds   3.0707   

        Lng              Hotel Name  
0  -68.3000         Albatross Hotel  
1  169.8464   Kaitangata Motor Camp  
2   27.8492  Mehamn Arctic Hotel AS  
3  168.8643           Ellie's Villa  
4  172.7902      Isles Sunset Lodge

In [17]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [18]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig



Figure(layout=FigureLayout(height='420px'))

In [29]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']=='Saint Pete Beach')
                                & (vacation_df['Hotel Name']=='Sirata Beach Resort')]
vacation_end = vacation_df.loc[(vacation_df['City']=='Saint Pete Beach')
                              & (vacation_df['Hotel Name']=='Sirata Beach Resort')]
vacation_stop1 = vacation_df.loc[(vacation_df['City']=='Houma')
                              & (vacation_df['Hotel Name']=='Courtyard by Marriott Houma')]
vacation_stop2 = vacation_df.loc[(vacation_df['City']=='Lufkin')
                                & (vacation_df['Hotel Name']=='Courtyard by Marriott Lufkin')] 
vacation_stop3 = vacation_df.loc[(vacation_df['City']=='Sevierville')
                                & (vacation_df['Hotel Name']=='The Lodge at Five Oaks')] 

In [30]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = pd.DataFrame(vacation_start[["Lat", "Lng"]]).to_numpy()
end = pd.DataFrame(vacation_end[["Lat", "Lng"]]).to_numpy()
stop1 = pd.DataFrame(vacation_stop1[["Lat", "Lng"]]).to_numpy()
stop2 = pd.DataFrame(vacation_stop2[["Lat", "Lng"]]).to_numpy()
stop3 = pd.DataFrame(vacation_stop3[["Lat", "Lng"]]).to_numpy()

start, stop1, stop2, stop3

(array([[ 27.7253, -82.7412]]),
 array([[ 29.5958, -90.7195]]),
 array([[ 31.3382, -94.7291]]),
 array([[ 35.8681, -83.5618]]))

In [32]:
# add the latitude/longitude
start=(27.7253, -82.7412)
end=(27.7253, -82.7412)
stop1=(29.5958, -90.7195)
stop2=(31.3382, -94.7291)
stop3=(35.8681, -83.5618)

In [33]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
itinerary_trip_plan = gmaps.directions_layer(start,end, 
                                             waypoints=[stop1,stop2,stop3],
                                             travel_mode="DRIVING")
fig.add_layer(itinerary_trip_plan)

fig


Figure(layout=FigureLayout(height='420px'))

In [35]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID              City Country  Max Temp Current Description      Lat  \
0      515  Saint Pete Beach      US     85.19     overcast clouds  27.7253   
1      396             Houma      US     84.20           clear sky  29.5958   
2      325            Lufkin      US     96.93           clear sky  31.3382   
3      341       Sevierville      US     80.20           clear sky  35.8681   

       Lng                    Hotel Name  
0 -82.7412           Sirata Beach Resort  
1 -90.7195   Courtyard by Marriott Houma  
2 -94.7291  Courtyard by Marriott Lufkin  
3 -83.5618        The Lodge at Five Oaks

In [37]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
itinerary_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
itinerary_locations = itinerary_df[["Lat", "Lng"]]

In [38]:
# 11a. Add a marker layer for each city to the map.
itinerary_locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(36.0, -76.0), zoom_level=5)
marker_layer = gmaps.marker_layer(itinerary_locations, info_box_content=itinerary_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))